-- admission_gate.lua
-- Atomic admission gate for NexusLLM.
-- MUST run on a dedicated standalone Redis instance (not cluster) because
-- the script touches keys with different hash slots.
--
-- Returns:
--   {'admitted', admission_token}             -- all checks passed
--   {'admitted_idempotent', existing_token}   -- request_id already admitted
--   {'rejected', dimension_string}            -- a limit was exceeded
--
-- Phase 1: all limit checks, ZERO mutations.
-- Phase 2: all mutations (only reached if every check passed).

redis.replicate_commands()

-- Capture server time once — never call TIME twice in same script.
local t      = redis.call('TIME')
local now_ms = tonumber(t[1]) * 1000 + math.floor(tonumber(t[2]) / 1000)

-- ── ARGV layout ───────────────────────────────────────────────────────────────
local request_id         = ARGV[1]
local admission_token    = ARGV[2]   -- UUID generated by caller before script execution
local est_input          = tonumber(ARGV[3])   -- estimated input tokens
local max_reservation    = tonumber(ARGV[4])   -- est_input + max_output_tokens (token count)
local rpm_window_ms      = tonumber(ARGV[5])   -- sliding window size, e.g. 60000
local tpm_ttl_s          = tonumber(ARGV[6])   -- TPM counter TTL, e.g. 70
local token_ttl_s        = tonumber(ARGV[7])   -- admission token TTL = auth expires_at seconds
local end_of_day_unix    = tonumber(ARGV[8])   -- UTC midnight Unix timestamp for daily key
local end_of_month_unix  = tonumber(ARGV[9])   -- end-of-month Unix timestamp
local heartbeat_stale_ms = tonumber(ARGV[10])  -- stale cutoff for inflight ZSET, e.g. 600000
local model_rpm_lim      = tonumber(ARGV[11])  -- 0 = unlimited
local model_itpm_lim     = tonumber(ARGV[12])
local project_rpm_lim    = tonumber(ARGV[13])
local project_itpm_lim   = tonumber(ARGV[14])
local project_inf_lim    = tonumber(ARGV[15])
local team_enforce_rpm   = ARGV[16]  -- '1' = enforce, '0' = record only
local team_rpm_lim       = tonumber(ARGV[17])
local team_enforce_tpm   = ARGV[18]
local team_itpm_lim      = tonumber(ARGV[19])
local daily_lim          = tonumber(ARGV[20])  -- 0 = unlimited
local monthly_lim        = tonumber(ARGV[21])
local org_monthly_lim    = tonumber(ARGV[22])

-- ── KEYS layout ───────────────────────────────────────────────────────────────
local model_rpm_key    = KEYS[1]   -- ZSET
local model_itpm_key   = KEYS[2]   -- STRING
local project_rpm_key  = KEYS[3]   -- ZSET
local project_itpm_key = KEYS[4]   -- STRING
local inflight_key     = KEYS[5]   -- ZSET (member=request_id, score=heartbeat_ms)
local team_rpm_key     = KEYS[6]   -- ZSET
local team_itpm_key    = KEYS[7]   -- STRING
local daily_key        = KEYS[8]   -- STRING (encodes scope + date)
local monthly_key      = KEYS[9]   -- STRING (encodes scope + month)
local org_monthly_key  = KEYS[10]  -- STRING (read-only check; incremented post-response)
local token_key        = KEYS[11]  -- STRING (admission token ownership)

-- ── Idempotency check ─────────────────────────────────────────────────────────
-- If this request_id is already in the project RPM ZSET, a prior admission
-- succeeded. Return idempotent success with the stored token so the caller
-- can verify ownership without double-counting any counter.
if redis.call('ZSCORE', project_rpm_key, request_id) then
    local existing_token = redis.call('GET', token_key)
    return {'admitted_idempotent', existing_token or ''}
end

-- ── Helpers ───────────────────────────────────────────────────────────────────
local function rpm_current(key)
    -- Prune expired entries from the sliding window, then count.
    redis.call('ZREMRANGEBYSCORE', key, '-inf', now_ms - rpm_window_ms)
    return tonumber(redis.call('ZCARD', key))
end

local function counter(key)
    return tonumber(redis.call('GET', key) or '0')
end

-- ── PHASE 1: ALL CHECKS, ZERO MUTATIONS ──────────────────────────────────────

-- Model RPM
if model_rpm_lim > 0 then
    if rpm_current(model_rpm_key) >= model_rpm_lim then
        return {'rejected', 'model_rpm_exceeded'}
    end
end

-- Model input TPM
if model_itpm_lim > 0 then
    if counter(model_itpm_key) + est_input > model_itpm_lim then
        return {'rejected', 'model_itpm_exceeded'}
    end
end

-- Project RPM
if project_rpm_lim > 0 then
    if rpm_current(project_rpm_key) >= project_rpm_lim then
        return {'rejected', 'project_rpm_exceeded'}
    end
end

-- Project input TPM
if project_itpm_lim > 0 then
    if counter(project_itpm_key) + est_input > project_itpm_lim then
        return {'rejected', 'project_itpm_exceeded'}
    end
end

-- Project concurrency (ZSET with heartbeat-based staleness pruning)
if project_inf_lim > 0 then
    redis.call('ZREMRANGEBYSCORE', inflight_key, '-inf', now_ms - heartbeat_stale_ms)
    if tonumber(redis.call('ZCARD', inflight_key)) >= project_inf_lim then
        return {'rejected', 'project_concurrency_exceeded'}
    end
end

-- Team RPM (conditional enforcement)
if team_enforce_rpm == '1' and team_rpm_lim > 0 then
    if rpm_current(team_rpm_key) >= team_rpm_lim then
        return {'rejected', 'team_rpm_exceeded'}
    end
end

-- Team input TPM (conditional enforcement)
if team_enforce_tpm == '1' and team_itpm_lim > 0 then
    if counter(team_itpm_key) + est_input > team_itpm_lim then
        return {'rejected', 'team_itpm_exceeded'}
    end
end

-- Daily quota (uses max_reservation for near-hard enforcement)
if daily_lim > 0 then
    if counter(daily_key) + max_reservation > daily_lim then
        return {'rejected', 'daily_quota_exceeded'}
    end
end

-- Monthly quota
if monthly_lim > 0 then
    if counter(monthly_key) + max_reservation > monthly_lim then
        return {'rejected', 'monthly_quota_exceeded'}
    end
end

-- Org monthly (read-only check; incremented post-response with actual tokens)
if org_monthly_lim > 0 then
    if counter(org_monthly_key) >= org_monthly_lim then
        return {'rejected', 'org_monthly_exceeded'}
    end
end

-- ── PHASE 2: ALL CHECKS PASSED — MUTATE ATOMICALLY ───────────────────────────

-- Model RPM sliding window
if model_rpm_lim > 0 then
    redis.call('ZADD', model_rpm_key, now_ms, request_id)
    redis.call('PEXPIRE', model_rpm_key, rpm_window_ms * 2)
end

-- Model input TPM
if model_itpm_lim > 0 then
    redis.call('INCRBY', model_itpm_key, est_input)
    redis.call('EXPIRE',  model_itpm_key, tpm_ttl_s)
end

-- Project RPM
redis.call('ZADD', project_rpm_key, now_ms, request_id)
redis.call('PEXPIRE', project_rpm_key, rpm_window_ms * 2)

-- Project input TPM
redis.call('INCRBY', project_itpm_key, est_input)
redis.call('EXPIRE',  project_itpm_key, tpm_ttl_s)

-- Project concurrency (ZSET; heartbeat updates score)
redis.call('ZADD', inflight_key, now_ms, request_id)
-- No global EXPIRE on inflight_key — members pruned by heartbeat staleness

-- Team RPM (always record for reporting, regardless of enforcement flag)
redis.call('ZADD', team_rpm_key, now_ms, request_id)
redis.call('PEXPIRE', team_rpm_key, rpm_window_ms * 2)

-- Team input TPM (always record)
redis.call('INCRBY', team_itpm_key, est_input)
redis.call('EXPIRE',  team_itpm_key, tpm_ttl_s)

-- Daily quota (max_reservation)
if daily_lim > 0 then
    redis.call('INCRBY', daily_key, max_reservation)
    redis.call('EXPIREAT', daily_key, end_of_day_unix)
end

-- Monthly quota (max_reservation)
if monthly_lim > 0 then
    redis.call('INCRBY', monthly_key, max_reservation)
    redis.call('EXPIREAT', monthly_key, end_of_month_unix)
end

-- Org monthly: NOT incremented here. Post-response only with actual tokens.

-- Admission token (ownership key for rollback and heartbeat)
redis.call('SET', token_key, admission_token, 'EX', token_ttl_s)

return {'admitted', admission_token}
