FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
COPY vendor/ vendor/
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -mod=vendor -ldflags="-w -s" -o /nexus-nodeagent ./cmd/nodeagent

FROM alpine:3.19
RUN apk add --no-cache \
    util-linux \
    numactl \
    coreutils \
    procps
COPY --from=builder /nexus-nodeagent /nexus-nodeagent
RUN mkdir -p /var/lib/nexus-agent
ENTRYPOINT ["/nexus-nodeagent"]
