-- Migration 004: intentionally empty
-- Models are NOT seeded. They are registered at runtime via:
--
--   POST /admin/v1/models/deploy
--
-- Example (Gemma on GPU 0,1):
--   curl -X POST http://localhost:8081/admin/v1/models/deploy \
--     -H "Content-Type: application/json" \
--     -d '{
--       "name":           "gemma-3-27b",
--       "display_name":   "Gemma 3 27B",
--       "provider":       "google",
--       "backend_type":   "vllm",
--       "image":          "vllm/vllm-openai:v0.4.3",
--       "hf_model_id":    "google/gemma-3-27b-it",
--       "host":           "localhost",
--       "port":           8000,
--       "gpu_devices":    [0, 1],
--       "tensor_parallel": 2,
--       "gpu_memory_util": 0.90,
--       "max_model_len":   32768,
--       "dtype":           "bfloat16",
--       "hf_token":        "hf_..."
--     }'
--
-- See README.md for full examples.
SELECT 1; -- no-op to make psql happy
