global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: nexus-gateway
    static_configs:
      - targets: ['nexus-gateway:9090']
    metrics_path: /metrics

  - job_name: nexus-admin
    static_configs:
      - targets: ['nexus-admin:9091']
    metrics_path: /metrics

  - job_name: nexus-scheduler
    static_configs:
      - targets: ['nexus-scheduler:9092']
    metrics_path: /metrics
